spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/workspace.db
    driver-class-name: org.sqlite.JDBC
    hikari.maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: com.leejb.jpa.workspace.dialect.SQLDialect
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: ictway
      password: ictway001
logging.level:
  org.hibernate.SQL: debug